### ISSUE TITLE
Missing license content

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/obs-service-download_url#1]
This source service is labeled as GPLv2+ in the source file, but there's no license file for the GPLv2. Can this be fixed, please?

This is necessary for me to package this source service in Fedora.

**Comment by seife** [comment]
https://github.com/openSUSE/obs-service-download_url/blob/master/download_url#L6

License is clearly stated in the source.
What benefit would it bring to include a license file that's probably 10 timese the size than the actual code?

**Comment by Conan-Kudo** [comment]
The GPLv2 requires a copy of the terms shipped with it, per clause 1 of the GPLv2.

**Comment by seife** [comment]
@adrianschroeter maybe relicensing under the WTFPL would be a good idea for this one... ;-)

**Comment by Conan-Kudo** [comment]
Please don't do that, because among other things WTFPL removes liability and warranty shields. It's really not hard to just include a copy of the license with the code.

**Comment by adrianschroeter** [comment]
added
